class Config {
  static String url = 'http://127.0.0.1:3000/';
  static String login = 'api/loginAdmin';
  static String category = 'Api/Category';
  static String allCategory = '/GetAllCategory';
  static String product = 'Api/Product';
  static String allProduct = '/GetAllProduct';
  static String createProduct = '/createProduct';
  static String deleteProduct = '/deleteProduct?productId=';
  static String updateProduct = '/updateProduct';
  static String user = 'api/users';
  static String allUser = '/getAllUser';
  static String setRole = '/setRole';
  static String banner = 'api/banner';
  static String allBanner = '/getAllBanner';
  static String createBanner = '/createBanner';
  static String deleteBanner = '/deleteBanner?bannerId=';
  static String updateBanner ='/updateBanner';
  static String createCategory = '/createCategory';
  static String deleteCategory = '/deleteCategory?categoryId=';
  static String updateCategory = '/updateCategory';
  static String storeHouse  ='api/house';
  static String checkQuantity = '/checkQuantity?productId=';
  static String updateQuantity ='/updateQuantity';
  static String order = 'Api/order';
  static String handleOrder ='/viewOrderXl';
  static String deliveryOrder = '/viewOrderGh';
  static String acceptedOrder ='/viewOrderNh';
  static String cancelOrder = '/viewOrderHuy';
  static String shipper = 'api/shipper';
  static String allShipper ='/getAllShipper';
  static String allAccountUser = '/getUser';
  static String allAccountAdmin = '/getAdmin';
  static String shipOrder ='/shipOrder';
  static String deleteOrder ='/deleteOrder?orderId=';
}
